### ISSUE TITLE
Global text changes

### ISSUE THREAD

**Issue by lutrov** [themegrill/easy-social-sharing#8]
From what I can see, this recommendation has already been posted on [wordpress.org](https://wordpress.org/support/topic/changing-of-some-phrases/) but I'd like to second it here.

* The text "Enable to All Screens"" should probably be something like "Display on all screens"
* The text "Enable to All Screens, Except For" should probably be something like "Display on all screens, except for"
* The text "Enable to Specific Screens" should probably be something like "Display on specific screens"

There may be other text strings which don't quite read correctly in English, and if you want me to, I can review them and make recommendations.

**Comment by lutrov** [comment]
Sorry, the general settings page (options-general.php?page=easy-social-sharing&tab=general) needs to reflect the new changes. The dynamic label should be changed to reflect the new changes:

1. Allow Specific Screens ==> Allow For All
2. Allow All Screens, Except For... ==> Allow For All, Except

While you're at it, consider changing "Custom Screen(s)" to just "Custom Screens". :-)

**Comment by shivapoudel** [comment]
@lutrov I have tweak the wording as defined in Custom Screen(s) select box. Also let Custom Screen(s) be as it is.
